# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 21:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['complexity'],
            },
        ),
        migrations.CreateModel(
            name='FAA_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('was_recreational', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('route', models.CharField(blank=True, max_length=500)),
                ('aircraft_ID', models.CharField(max_length=10)),
                ('duration', models.FloatField(default=0.0)),
                ('command_practice', models.FloatField(default=0.0)),
                ('actual', models.FloatField(default=0.0)),
                ('hood', models.FloatField(default=0.0)),
                ('night', models.FloatField(default=0.0)),
                ('CFI', models.FloatField(default=0.0)),
                ('dual', models.FloatField(default=0.0)),
                ('XC', models.FloatField(default=0.0)),
                ('PIC', models.FloatField(default=0.0)),
                ('SIC', models.FloatField(default=0.0)),
                ('solo', models.FloatField(default=0.0)),
                ('night_actual', models.FloatField(default=0.0)),
                ('XC_actual', models.FloatField(default=0.0)),
                ('night_hood', models.FloatField(default=0.0)),
                ('XC_hood', models.FloatField(default=0.0)),
                ('XC_night', models.FloatField(default=0.0)),
                ('PIC_XC', models.FloatField(default=0.0)),
                ('SIC_XC', models.FloatField(default=0.0)),
                ('solo_XC', models.FloatField(default=0.0)),
                ('ILS', models.IntegerField(default=0)),
                ('VOR', models.IntegerField(default=0)),
                ('NDB', models.IntegerField(default=0)),
                ('LOC', models.IntegerField(default=0)),
                ('BC', models.IntegerField(default=0)),
                ('GPS', models.IntegerField(default=0)),
                ('ASR', models.IntegerField(default=0)),
                ('AR', models.IntegerField(default=0.0)),
                ('day_landings', models.IntegerField(default=0.0)),
                ('night_landings', models.IntegerField(default=0.0)),
                ('faa_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.FAA_part')),
            ],
        ),
        migrations.CreateModel(
            name='Make_and_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.Engine')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.Equipment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='make_and_model',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.Manufacturer'),
        ),
        migrations.AddField(
            model_name='flight',
            name='make_and_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logbook.Make_and_model'),
        ),
        migrations.AddField(
            model_name='flight',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
